apiVersion: apps/v1
kind: Deployment
metadata:
  name: queueoke
  namespace: queue
  labels:
    app: queueoke
spec:
  selector:
    matchLabels:
      app: queueoke
  template:
    metadata:
      labels:
        app: queueoke
    spec:
      containers:
      - name: queueoke
        image: iad.ocir.io/id6dibaakt36/mgarciar/queueoke:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        env:
            - name: DP_ENDPOINT
              value: "https://cell-1.queue.messaging.us-ashburn-1.oci.oraclecloud.com"
            - name: QUEUE_ID
              value: "ocid1.queue.oc1.iad.amaaaaaaj6ty54aaabrmdjhf76p7fhyd3lev2exbvlxk4qoctwexn6dn2fna"
      imagePullSecrets:
      - name: queueoke-secret