apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: http-so
  namespace: queue
  labels:
    deploymentName: queue-deployment-so
spec:
  pollingInterval: 5 #Interval for polling
  maxReplicaCount: 75
  idleReplicaCount: 0 # When idle, scale-in to 0 pods
  minReplicaCount: 1
  cooldownPeriod: 120 # Optional. Default: 300 seconds
  scaleTargetRef:
    name: queueoke
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "200"
        url: "https://e7fqri2v3weyzypanm6vzgqtmu.apigateway.us-ashburn-1.oci.customer-oci.com/queue/v1/getQueueStat"
        valueLocation: 'queue.visibleMessages'